name: Branch Comparison Analysis and Deployment

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes
  workflow_dispatch:     # Allow manual trigger
  push:
    branches:
      - release             # Run on pushes to release branch

jobs:
  analyze-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Needed for pushing to gh-pages
      pages: write       # Needed for GitHub Pages deployment
      id-token: write    # Needed for GitHub Pages deployment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Run branch analysis for latest
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          GITHUB_REPO: ${{ github.repository }}
          MAIN_BRANCH: main
          RELEASE_BRANCH: release
        run: |
          # Run analysis for latest
          python github_branch_analyzer_with_date.py
          python analyze_branch_data_with_date.py

      - name: Setup visualization directory
        run: |
          # Create visualization directory if it doesn't exist
          mkdir -p visualization
          
          # Copy analysis results
          cp analyzed_branch_data*.json visualization/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: visualization
          branch: gh-pages
          clean: true
